name: qiblah_search
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Qiblah
  piri_qiblah:
    git:
      url: https://github.com/celikdemirrberkay/piri_qiblah.git
      ref: 75c4bf91acf7363619f6052fe3cb753e5bb7efce

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    # You can add specific assets here like:
    # - assets/images/your_image.png
    # - assets/fonts/your_font.ttf
